UC_REQUIREMENTS = {
    "UCSD": {
        "Java Programming": [["CSE 8B", "B", 1], ["CSE 11", "A", 1]],
        "Data Structures": [["CSE 12", "A", 1]],
        "Discrete Math": [["CSE 20", "A", 1]],
        "Calculus I": [["MATH 20A", "A", 1]],
        "Calculus II": [["MATH 20B", "B", 1]],
        "Calculus III": [["MATH 20C", "C", 1]],
        "Linear Algebra": [["MATH 18", "D", 1]],
    },
    "UCI": {
        "Calculus I": [["MATH 2A", "A", 1]],
        "Calculus II": [["MATH 2B", "B", 1]],
        "Intro to CS I": [["I&C SCI 31", "C", 1]],
        "Intro to CS II": [["I&C SCI 32", "D", 1]],
        "Intro to CS III": [["I&C SCI 33", "E", 1]],
    },
    "UCD": {
        "Calculus I": [["MAT 021A", "A", 1]],
        "Calculus II": [["MAT 021B", "B", 1]],
        "Calculus III": [["MAT 021C", "C", 1]],
        "Discrete Math": [["ECS 020", "D", 1]],
        "Java Programming": [["ECS 036A", "E", 1]],
        "Data Structures": [["ECS 036B", "F", 1]],
        "Advanced CS": [["ECS 036C", "G", 1]],
        "Assembly / Architecture": [["ECS 050", "H", 1]],
    },
    "UCR": {
        "Intro to CS I": [["CS 10A", "A", 1]],
        "Intro to CS II": [["CS 10B", "B", 1]],
        "Calculus I": [["MATH 9A", "C", 1]],
        "Calculus II": [["MATH 9B", "D", 1]],
        "Calculus III": [["MATH 9C", "E", 1]],
    },
    "UCLA": {
        "Calculus I": [["MATH 31A", "A", 1]],
        "Calculus II": [["MATH 31B", "B", 1]],
        "Multivariable Calc I": [["MATH 32A", "C", 1]],
        "Multivariable Calc II": [["MATH 32B", "D", 1]],
        "Linear Algebra": [["MATH 33A", "E", 1]],
        "Intro to CS": [["COM SCI 31", "G", 1]],
    },
    "UCB": {
        "Calculus I": [["MATH 1A", "A", 1]],
        "Calculus II": [["MATH 1B", "B", 1]],
        "Multivariable Calculus": [["MATH 53", "C", 1]],
        "Linear Algebra / Diff Eq": [["MATH 54", "D", 1]],
    },
    "UCM": {
        "Java Programming": [["CSE 020", "C", 1]],
        "Discrete Math": [["CSE 021", "D", 1]],
        "Data Structures": [["CSE 030", "E", 1]],
        "Calculus I": [["MATH 021", "F", 1]],
        "Calculus II": [["MATH 022", "G", 1]],
        "Calculus III": [["MATH 023", "H", 1]],
        "Linear Algebra": [["MATH 024", "I", 1]],
    },
    "UCSC": {
        "Data Structures": [["CSE 12", "A", 1]],
        "Discrete Math": [["CSE 16", "B", 1]],
        "Systems Programming": [["CSE 30", "C", 1]],
        "Calculus I": [["MATH 19A", "D", 1], ["MATH 20A", "D", 1]],
        "Calculus II": [["MATH 19B", "E", 1], ["MATH 20B", "E", 1]],
    },
    "UCSB": {
        "Calculus I": [["MATH 3A", "A", 1]],
        "Calculus II": [["MATH 3B", "B", 1]],
        "Linear Algebra": [["MATH 4A", "C", 1]],
        "Differential Equations": [["MATH 4B", "D", 1]],
        "Intro to Programming": [["CMPSC 16", "E", 1]],
        "Data Structures": [["CMPSC 24", "F", 1]],
        "Discrete Math": [["CMPSC 40", "G", 1]],
    }
}
